server: 
  port: 7001
 
eureka: 
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
#    hostname: 127.0.0.1 #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      

# eureka7001安全认证的配置,微服务microservicecloud-provider-dept-8001注册进eureka7001需修改yml添加用户名密码
security:
  basic:
    enabled: true  #开启基于HTTP basic的认证
  user:
    name: root  # 用户名
    password: root   # 用户密码

 